// Generated by Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

@interface NSNumber (SWIFT_EXTENSION(PlaywireSDK))
@end


SWIFT_CLASS("_TtC11PlaywireSDK18PlaywireAPIManager")
@interface PlaywireAPIManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class PlaywireCreativeFeeder;

SWIFT_CLASS("_TtC11PlaywireSDK17PlaywireAdManager")
@interface PlaywireAdManager : NSObject
@property (nonatomic, readonly, strong) PlaywireCreativeFeeder * _Nonnull creativeFeeder;
- (void)configureView;
- (void)presentAd;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class NSCoder;

SWIFT_CLASS("_TtC11PlaywireSDK29PlaywireAdManagerActivityView")
@interface PlaywireAdManagerActivityView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithManager:(PlaywireAdManager * _Nonnull)manager;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC11PlaywireSDK25PlaywireConfigFileManager")
@interface PlaywireConfigFileManager : PlaywireAPIManager
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PlaywireConfigFileManager * _Nonnull sharedInstance;)
+ (PlaywireConfigFileManager * _Nonnull)sharedInstance;
@end


SWIFT_CLASS("_TtC11PlaywireSDK22PlaywireCreativeFeeder")
@interface PlaywireCreativeFeeder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class UIViewController;

SWIFT_CLASS("_TtC11PlaywireSDK27PlaywireFullScreenAdManager")
@interface PlaywireFullScreenAdManager : PlaywireAdManager
- (nonnull instancetype)initWithAuth:(NSString * _Nonnull)auth controller:(UIViewController * _Nullable)controller;
- (void)presentAd;
@end

@class UIWebView;
@protocol PlaywireViewDelegate;

SWIFT_CLASS("_TtC11PlaywireSDK12PlaywireView")
@interface PlaywireView : UIView <UIWebViewDelegate>
@property (nonatomic, weak) id <PlaywireViewDelegate> _Nullable delegate;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)preparePlayer;
- (BOOL)webView:(UIWebView * _Nonnull)webView shouldStartLoadWithRequest:(NSURLRequest * _Nonnull)request navigationType:(UIWebViewNavigationType)navigationType;
- (void)stop;
- (void)start;
- (void)webViewDidFinishLoad:(UIWebView * _Nonnull)webView;
@end


SWIFT_PROTOCOL("_TtP11PlaywireSDK20PlaywireViewDelegate_")
@protocol PlaywireViewDelegate
@optional
- (void)playwireViewWithPlaywireView:(PlaywireView * _Nonnull)playwireView playerTimeOutWithTime:(double)time;
- (void)playwireViewWithPlaywireView:(PlaywireView * _Nonnull)playwireView playerReadyWithParams:(NSDictionary<NSString *, id> * _Nullable)params;
- (void)playwireViewWithPlaywireView:(PlaywireView * _Nonnull)playwireView adRequestedWithParams:(NSDictionary<NSString *, id> * _Nullable)params;
- (void)playwireViewWithPlaywireView:(PlaywireView * _Nonnull)playwireView adStartedWithParams:(NSDictionary<NSString *, id> * _Nullable)params;
- (void)playwireViewWithPlaywireView:(PlaywireView * _Nonnull)playwireView adErrorWithParams:(NSDictionary<NSString *, id> * _Nullable)params;
- (void)playwireViewWithPlaywireView:(PlaywireView * _Nonnull)playwireView adCompleteWithParams:(NSDictionary<NSString *, id> * _Nullable)params;
- (void)playwireViewWithPlaywireView:(PlaywireView * _Nonnull)playwireView adClickedWithParams:(NSDictionary<NSString *, id> * _Nullable)params;
@end

@protocol PlaywireViewControllerDelegate;
@class NSBundle;

SWIFT_CLASS("_TtC11PlaywireSDK22PlaywireViewController")
@interface PlaywireViewController : UIViewController <PlaywireViewDelegate>
@property (nonatomic, weak) id <PlaywireViewControllerDelegate> _Nullable delegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)presentOnViewControllerWithController:(UIViewController * _Nonnull)controller animated:(BOOL)animated dismiss:(void (^ _Nullable)(void))dismiss;
- (void)preparePlayer;
- (void)playwireViewWithPlaywireView:(PlaywireView * _Nonnull)playwireView playerReadyWithParams:(NSDictionary<NSString *, id> * _Nullable)params;
- (void)playwireViewWithPlaywireView:(PlaywireView * _Nonnull)playwireView playerTimeOutWithTime:(double)time;
- (void)playwireViewWithPlaywireView:(PlaywireView * _Nonnull)playwireView adErrorWithParams:(NSDictionary<NSString *, id> * _Nullable)params;
- (void)playwireViewWithPlaywireView:(PlaywireView * _Nonnull)playwireView adCompleteWithParams:(NSDictionary<NSString *, id> * _Nullable)params;
- (void)playwireViewWithPlaywireView:(PlaywireView * _Nonnull)playwireView adClickedWithParams:(NSDictionary<NSString *, id> * _Nullable)params;
@property (nonatomic, readonly) BOOL isReady;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP11PlaywireSDK30PlaywireViewControllerDelegate_")
@protocol PlaywireViewControllerDelegate
@optional
- (void)playwireViewControllerWithPlaywireViewController:(PlaywireViewController * _Nonnull)playwireViewController playerTimeOutWithTime:(double)time;
- (void)playwireViewControllerWithPlaywireViewController:(PlaywireViewController * _Nonnull)playwireViewController playerReadyWithParams:(NSDictionary<NSString *, id> * _Nullable)params;
@end


SWIFT_CLASS("_TtC11PlaywireSDK29PlaywireViewControllerManager")
@interface PlaywireViewControllerManager : NSObject <PlaywireViewControllerDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable auth;)
+ (NSString * _Nullable)auth;
+ (void)setAuth:(NSString * _Nullable)newAuth;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PlaywireViewControllerManager * _Null_unspecified sharedInstance;)
+ (PlaywireViewControllerManager * _Null_unspecified)sharedInstance;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (NSString * _Nonnull)playwireApplicationId;
- (void)showRewardedVideoOnControllerWithController:(UIViewController * _Nonnull)controller dismiss:(void (^ _Nullable)(void))dismiss;
@property (nonatomic, readonly) BOOL isReady;
@end



SWIFT_CLASS("_TtC11PlaywireSDK27PlaywireViewHolderAdManager")
@interface PlaywireViewHolderAdManager : PlaywireAdManager
- (nonnull instancetype)initWithAuth:(NSString * _Nonnull)auth controller:(UIViewController * _Nonnull)controller view:(UIView * _Nonnull)view OBJC_DESIGNATED_INITIALIZER;
- (void)presentAd;
@end


@interface UIDevice (SWIFT_EXTENSION(PlaywireSDK))
@property (nonatomic, readonly, copy) NSString * _Nonnull modelName;
@end

#pragma clang diagnostic pop
